
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '<\xbf\xe6\xccc\xa5\x9f\xddjX\xbe~0\xcdg\xeb'
    
_lr_action_items = {'MAP':([13,25,26,32,40,],[17,17,17,17,17,]),':':([9,22,38,],[13,32,45,]),'GROUP':([0,1,4,5,6,11,14,24,27,30,43,],[-1,7,-2,-3,-4,-7,-5,-8,-9,-6,-10,]),'STRING':([2,3,7,12,13,16,23,25,26,28,29,32,40,44,46,52,54,],[8,9,10,-18,18,22,-19,18,18,35,38,18,18,35,-20,-18,22,]),'INT':([42,45,],[48,50,]),'=':([35,],[42,]),'ENUM':([0,1,4,5,6,11,14,24,27,30,43,],[-1,3,-2,-3,-4,-7,-5,-8,-9,-6,-10,]),'LIST':([13,25,26,32,40,],[19,19,19,19,19,]),',':([18,33,36,37,41,48,49,51,],[-21,40,44,-11,-22,-13,-12,-23,]),'>':([18,34,41,47,51,],[-21,41,-22,51,-23,]),';':([18,39,41,51,],[-21,46,-22,-23,]),'MSG':([15,21,31,53,55,],[-14,29,-15,-16,-17,]),'{':([8,10,18,20,41,50,51,],[12,15,-21,28,-22,52,-23,]),'$end':([0,1,4,5,6,11,14,24,27,30,43,],[-1,0,-2,-3,-4,-7,-5,-8,-9,-6,-10,]),'}':([12,15,16,21,23,31,36,37,46,48,49,52,53,54,55,],[-18,-14,24,30,-19,-15,43,-11,-20,-13,-12,-18,-16,55,-17,]),'<':([17,19,],[25,26,]),'STRUCT':([0,1,4,5,6,11,14,24,27,30,43,],[-1,2,-2,-3,-4,-7,-5,-8,-9,-6,-10,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'group':([1,],[4,]),'struct':([1,],[5,]),'enum_contents':([20,],[27,]),'struct_contents':([8,],[11,]),'msg_contents':([50,],[53,]),'type':([13,25,26,32,40,],[20,33,34,39,47,]),'enum':([1,],[6,]),'list':([0,],[1,]),'field':([16,54,],[23,23,]),'enumval_list':([28,],[36,]),'message_list':([15,],[21,]),'message':([21,],[31,]),'enumval':([28,44,],[37,49,]),'group_contents':([10,],[14,]),'field_list':([12,52,],[16,54,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> list","S'",1,None,None,None),
  ('list -> <empty>','list',0,'p_list_empty','msggen.py',97),
  ('list -> list group','list',2,'p_list_group','msggen.py',104),
  ('list -> list struct','list',2,'p_list_struct','msggen.py',108),
  ('list -> list enum','list',2,'p_list_enum','msggen.py',112),
  ('group -> GROUP STRING group_contents','group',3,'p_group','msggen.py',118),
  ('group_contents -> { message_list }','group_contents',3,'p_group_contents','msggen.py',121),
  ('struct -> STRUCT STRING struct_contents','struct',3,'p_struct','msggen.py',126),
  ('struct_contents -> { field_list }','struct_contents',3,'p_struct_contents','msggen.py',130),
  ('enum -> ENUM STRING : type enum_contents','enum',5,'p_enum','msggen.py',135),
  ('enum_contents -> { enumval_list }','enum_contents',3,'p_enum_contents','msggen.py',139),
  ('enumval_list -> enumval','enumval_list',1,'p_enumval_list','msggen.py',142),
  ('enumval_list -> enumval_list , enumval','enumval_list',3,'p_enumval_list','msggen.py',143),
  ('enumval -> STRING = INT','enumval',3,'p_enumval','msggen.py',150),
  ('message_list -> <empty>','message_list',0,'p_message_list','msggen.py',155),
  ('message_list -> message_list message','message_list',2,'p_message_list','msggen.py',156),
  ('message -> MSG STRING : INT msg_contents','message',5,'p_message','msggen.py',163),
  ('msg_contents -> { field_list }','msg_contents',3,'p_msg_contents','msggen.py',172),
  ('field_list -> <empty>','field_list',0,'p_field_list','msggen.py',177),
  ('field_list -> field_list field','field_list',2,'p_field_list','msggen.py',178),
  ('field -> STRING : type ;','field',4,'p_field','msggen.py',185),
  ('type -> STRING','type',1,'p_type','msggen.py',190),
  ('type -> LIST < type >','type',4,'p_type','msggen.py',191),
  ('type -> MAP < type , type >','type',6,'p_type','msggen.py',192),
]
