- !node/GuiOutput
  jpeg quality: 85
  image_in<-image_out: !node/HoughLines
    maxLineGap: 5
    minLineLength: 15
    probabalistic: true
    rho: 1
    srn: 0
    stn: 0
    theta: 0.01745329238474369
    threshold: 15
    image_in<-image_out: !node/Canny
      L2 gradient: 0
      aperture size: 3
      threshold 1: 30.0
      threshold 2: 80.0
      image_in<-image (not copied): !node/MedianFilter
        kernel: 9
        image<-image (not copied): !node/Levels
          black level: 50
          white level: 100
          image<-image_out: !node/Resize
            interpolation mode: 1
            scale factor: 0.10000000149011612
            image_in<-H: &SplitHSV_1 !node/SplitHSV
              image<-image: &FileInput_1 !node/FileInput {filename: /media/JWYATT13M-E/d3}
- !node/GuiOutput
  jpeg quality: 85
  image_in<-image: *FileInput_1
- !node/Centre
  Name: pipe
  image_in<-Pixels: !node/HistogramSegmentation
    Bin: 11
    Number of bins: 42
    image_in<-H: *SplitHSV_1
- !node/Histogram
  Channel type: Hue
  Number of bins: 42
  image_in<-H: *SplitHSV_1
