Ssrc C++/Lua/Perl/Python/Ruby Bindings for Spread API: ssrc::spread::detail::Buffer< type > Class Template Reference
ssrc::spread::detail::Buffer< type > Class Template Reference
#include <Buffer.h>
Detailed Description
template<typename type>
class ssrc::spread::detail::Buffer< type >
Buffer defines a limited set of operations for managing a memory buffer.
It is intended only for internal use by the library. Please do not subclass Buffer, but do examine its public methods that are inherited by its subclasses.
We define Buffer instead of using std::vector because we want to avoid the overhead of std::vector::clear() and std::vector::resize(), both of which cause unused data elements to be erased. The buffers used by the library may be resized often (potentially on every send and receive). We are unconcerned with erasing (or initializing) unused elements because we read and write to the buffer's raw memory. Therefore, we merely require an index that tracks the size of the buffer.
Definition at line 50 of file Buffer.h.
Public Types
typedef type value_type
typedef value_type & reference
typedef const reference const_reference
typedef value_type * pointer
typedef const pointer const_pointer
Public Member Functions
Buffer (const unsigned int capacity)
Creates a buffer with the specified capacity and sets its size to zero.
~Buffer ()
Deallocates all memory used by the buffer.
unsigned int capacity () const
Returns the maximum number of elements that can be written to the buffer without reallocating memory.
reference operator[] (const unsigned int index)
Returns the element at the specified index.
const_reference operator[] (const unsigned int index) const
Returns the element at the specified index.
void reserve (const unsigned int capacity)
Increases the buffer capacity to the specified size.
void resize (const unsigned int size)
Resizes the buffer to the specified size.
unsigned int size () const
Returns the number of elements contained in the buffer.
void clear ()
Same as resize(0).
void add (const type &value)
Appends a value to the end of the buffer and increments the size by one.
Member Typedef Documentation
template<typename type> typedef type ssrc::spread::detail::Buffer< type >::value_type
Definition at line 57 of file Buffer.h.
template<typename type> typedef value_type& ssrc::spread::detail::Buffer< type >::reference
Definition at line 58 of file Buffer.h.
template<typename type> typedef const reference ssrc::spread::detail::Buffer< type >::const_reference
Definition at line 59 of file Buffer.h.
template<typename type> typedef value_type* ssrc::spread::detail::Buffer< type >::pointer
Definition at line 60 of file Buffer.h.
template<typename type> typedef const pointer ssrc::spread::detail::Buffer< type >::const_pointer
Definition at line 61 of file Buffer.h.
Constructor & Destructor Documentation
template<typename type> ssrc::spread::detail::Buffer< type >::Buffer (const unsigned int capacity) [inline, explicit]
Creates a buffer with the specified capacity and sets its size to zero.
Parameters:
capacity The initial capacity of the buffer.
Definition at line 68 of file Buffer.h.
template<typename type> ssrc::spread::detail::Buffer< type >::~Buffer () [inline]
Deallocates all memory used by the buffer.
Definition at line 75 of file Buffer.h.
Member Function Documentation
template<typename type> unsigned int ssrc::spread::detail::Buffer< type >::capacity () const [inline]
Returns the maximum number of elements that can be written to the buffer without reallocating memory.
Returns:
The buffer capacity.
Definition at line 83 of file Buffer.h.
Referenced by ssrc::spread::detail::ByteBuffer::ByteBuffer().
template<typename type> reference ssrc::spread::detail::Buffer< type >::operator[] (const unsigned int index) [inline]
Returns the element at the specified index.
Parameters:
index The index of the element to retrieve.
Returns:
The element at the specified index.
Definition at line 93 of file Buffer.h.
template<typename type> const_reference ssrc::spread::detail::Buffer< type >::operator[] (const unsigned int index) const [inline]
Returns the element at the specified index.
Parameters:
index The index of the element to retrieve.
Returns:
The element at the specified index.
Definition at line 103 of file Buffer.h.
template<typename type> void ssrc::spread::detail::Buffer< type >::reserve (const unsigned int capacity) [inline]
Increases the buffer capacity to the specified size.
If the new size is less than or equal to the buffer capacity, no action is performed. If the size is greater than the capacity, new memory is reserved, increasing the capacity while preserving the existing buffer contents.
Parameters:
capacity The new buffer capacity.
Definition at line 116 of file Buffer.h.
template<typename type> void ssrc::spread::detail::Buffer< type >::resize (const unsigned int size) [inline]
Resizes the buffer to the specified size.
If the new size is less than or equal to the buffer capacity, the size is simply set to the new value. If the size is greater than the capacity, new memory is reserved—preserving the existing buffer contents—before setting the size to the new value.
Parameters:
size The new buffer size.
Definition at line 135 of file Buffer.h.
Referenced by ssrc::spread::BaseMessage::get_membership_info().
template<typename type> unsigned int ssrc::spread::detail::Buffer< type >::size () const [inline]
Returns the number of elements contained in the buffer.
Returns:
The number of elements contained in the buffer.
Reimplemented in ssrc::spread::Message.
Definition at line 144 of file Buffer.h.
Referenced by ssrc::spread::detail::ByteBuffer::ByteBuffer(), ssrc::spread::BaseMessage::get_membership_info(), and ssrc::spread::detail::ByteBuffer::operator=().
template<typename type> void ssrc::spread::detail::Buffer< type >::clear () [inline]
Same as resize(0).
Reimplemented in ssrc::spread::detail::ByteBuffer, and ssrc::spread::Message.
Definition at line 149 of file Buffer.h.
template<typename type> void ssrc::spread::detail::Buffer< type >::add (const type & value) [inline]
Appends a value to the end of the buffer and increments the size by one.
If the buffer is at full capacity, its capacity is increased to be able to hold more data. Currently, this is done by doubling the current capacity, but you should not rely on that behavior.
Parameters:
value The value to append to the buffer.
Definition at line 162 of file Buffer.h.
The documentation for this class was generated from the following file:
Buffer.h
Copyright © 2006-2009 Savarese Software Research Corporation. All rights reserved.